// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BounceApp
{
	public partial class SecondViewController : UIViewController
	{
		private bool buttonFlashing = false;

		public SecondViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			BtnClickMe.TouchUpInside += (sender, e) => {
				StartAnimation();
			};

		}

		private void StartAnimation()
		{
			if (buttonFlashing)
				return;
			HeaderLabel.Alpha = 1.0f;
			UIView.AnimateNotify(0.12f, 0.0f, UIViewAnimationOptions.CurveEaseInOut | UIViewAnimationOptions.Repeat
								 | UIViewAnimationOptions.Autoreverse | UIViewAnimationOptions.AllowUserInteraction, () => {
									 HeaderLabel.Alpha = 0.0f;
								 }, (finished) => {
								 });
		}

		private void StopAnimation()
		{
			if (!buttonFlashing)
				return;
			UIView.AnimateNotify(0.12f, 0.0f, UIViewAnimationOptions.CurveEaseInOut | UIViewAnimationOptions.BeginFromCurrentState, () => {
				HeaderLabel.Alpha = 1.0f;
			}, (finished) => {
			});
		}
	}
}
